require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe OutBreaksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # OutBreak. As you add validations to OutBreak, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      report_date: Date.new(2001,12),
      state: "Florida",
      primary_mode: "person-to-person",
      etiology: "Norovirus Genogroup II",
      serotype_or_genotype: "confirmed",
      etiology_status: "Norovirus Genogroup II",
      setting: "Diner",
      illnesses: 33,
      hospitalizations: 11,
      deaths: 2
    }
  }

  let(:invalid_attributes) {
    {
      report_date: "Date.new(2001,12)",
      state: 1231,
      primary_mode: 123,
      etiology: 123,
      serotype_or_genotype: 123,
      etiology_status: 123, 
      setting: 123,
      illnesses: "33",
      hospitalizations: "11",
      deaths: "2"
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OutBreaksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      # out_break = OutBreak.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      out_break = OutBreak.create! valid_attributes
      get :show, params: {id: out_break.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OutBreak" do
        expect {
          post :create, params: {out_break: valid_attributes}, session: valid_session
        }.to change(OutBreak, :count).by(1)
      end

      it "renders a JSON response with the new out_break" do
        post :create, params: {out_break: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.media_type).to eq('application/json')
        expect(response.location).to eq(out_break_url(OutBreak.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new out_break" do
        post :create, params: {out_break: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.media_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          report_date: Date.new(2020,12),
          state: "Alabame",
          primary_mode: "animal-to-person",
          etiology: "Norovirus Genogroup II",
          serotype_or_genotype: "confirmed",
          etiology_status: "Norovirus Genogroup II",
          setting: "Bar",
          illnesses: 21,
          hospitalizations: 12,
          deaths: 22
        }
      }

      it "updates the requested out_break" do
        out_break = OutBreak.create! valid_attributes
        put :update, params: {id: out_break.to_param, out_break: new_attributes}, session: valid_session
        expect { out_break.reload }.to change(out_break, :updated_at)
      end

      it "renders a JSON response with the out_break" do
        out_break = OutBreak.create! valid_attributes
        put :update, params: {id: out_break.to_param, out_break: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.media_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the out_break" do
        out_break = OutBreak.create! valid_attributes
        put :update, params: {id: out_break.to_param, out_break: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.media_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested out_break" do
      out_break = OutBreak.create! valid_attributes
      expect {
        delete :destroy, params: {id: out_break.to_param}, session: valid_session
      }.to change(OutBreak, :count).by(-1)
    end
  end

end
